apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment-develop
  namespace: kubernetes-cluster-utkarshgoyal
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cluster-1
  template:
    metadata:
      labels:
        app: cluster-1
    spec:
      containers:
      - name: cluster-1
        image: utkarshgoyal/samplekubernetes:latest-develop
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-1-develop
  namespace: kubernetes-cluster-utkarshgoyal
spec:
  type: NodePort
  selector:
    app: cluster-1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30158